### 抛出异常

在定义函数的时候，在函数内部把异常抛出来然后交给调用函数的人来处理

```python
def division(n1, n2):
    # 函数里面不处理这个问题，将问题抛出
    if n2 == 0:
        raise ZeroDivisionError('除数不能为0')
    result = n1 / n2
    return result


try:
    division(4, 0)
except ZeroDivisionError as e:
    print(e)
```



### 自定义异常

你可以用raise语句来引发一个异常。异常/错误对象必须有一个名字，且它们应是Error或Exception类的子类

当需要使用的异常不存在时，可以自己可以定义一个异常类型

```python
class LengthError(Exception):
    def __init__(self, min, max):
        self.min = min
        self.max = max

    def __str__(self):
        return '长度必须是{}到{}'.format(self.min, self.max)


password = input('密码：')


def check_password(pwd):
    #
    if not 12 >= len(pwd) >= 6:
        # print('长度不正确')
        raise LengthError(6, 12)
    else:
        print('密码是：{}'.format(pwd))


# check_password(password)
try:
    check_password(password)
except LengthError as e:
    print('长度错误')
    print(e)
else:
    print('欢迎登录')
```

